name: Deployment to INT
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - force-app/**
    branches:
      - main
permissions:
  contents: read
  security-events: write
  # only required for workflows in private repositories
  actions: read
jobs:
  deployment-to-int:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
      - name: Populate auth file with SFDX_URL secret of target org
        run: |
          echo ${{ secrets.INT_SFDX_URL}} > ./INT_SFDX_URL.txt
      - name: Authenticate to target Org
        run: sf org login sfdx-url -f ./INT_SFDX_URL.txt -s -a targetOrg
      - name: Installing sfdx git delta
        run: |
          echo y | sf plugins install sfdx-git-delta
          sf plugins
      - name: Create delta packages for new, modified or deleted metadata
        run: >
          mkdir changed-sources
          
          sf sgd source delta --to "HEAD" --from "HEAD^" --output-dir ./changed-sources/ --generate-delta --source-dir ./force-app/ 
      - name: Installing java
        run: sudo apt-get update && sudo apt-get install default-jdk
      - name: Installing SFDX scanner
        run: sf plugins install code-analyzer
      - name: Analize code
        run: sf code-analyzer run --rule-selector Recommended --workspace ./changed-sources --target ./changed-sources/**/*.cls --severity-threshold 2 --output-file ./changed-sources/apexScanResults.sarif --view detail
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ./changed-sources/apexScanResults.sarif
      - name: Read PR Body
        env:
          PR_BODY: ${{github.event.pull_request.body}}
        run: |
          
          FILE=./parsePR.js 
          if test -f "$FILE"; then
              echo $PR_BODY > ./pr_body.txt
              node ./parsePR.js              
              TESTS=$(cat testsToRun.txt)
              echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV     
          else
              TESTS=all
              echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV 
          fi
      - name: Deployment - run specified tests
        if: ${{ env.APEX_TESTS != 'all' }}
        run: >
          echo ${{env.APEX_TESTS}}

          sf project deploy start --ignore-conflicts --source-dir ./changed-sources/force-app --test-level RunSpecifiedTests --tests ${{env.APEX_TESTS}} --json
      - name: Deployment - run all tests
        if: ${{ env.APEX_TESTS == 'all' }}
        run: >
          echo ${{env.APEX_TESTS}}

          sf project deploy start --ignore-conflicts --source-dir ./changed-sources/force-app --test-level RunLocalTests --json
# 